name: Transition Clubhouse on Prerelease
on:
  release:
    types: ['published']

jobs:
  prerelease-stories:
    runs-on: ubuntu-latest
    steps:
      - uses: farmersdog/clubhouse-workflow-action@v1
        if: github.event.release.prerelease
        with:
          clubhouseToken: ${{ secrets.CLUBHOUSE_TOKEN }}
          addReleaseInfo: true
          endStateName: 'Release Candidate'
