name: clubhouse workflow e2e test
on:
  release:
    types: ['released']

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Test master
        uses: farmersdog/clubhouse-workflow-action@master
        with:
          clubhouseToken: ${{ secrets.CLUBHOUSE_TOKEN }}
          endStateName: Completed
          addReleaseInfo: true
      - name: Test latest v1 release
        uses: farmersdog/clubhouse-workflow-action@v1
        with:
          clubhouseToken: ${{ secrets.CLUBHOUSE_TOKEN }}
          endStateName: Completed
          addReleaseInfo: true
