name: clubhouse workflow e2e test
on:
  release:
    types: ['released']

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: farmersdog/clubhouse-workflow-action@master
        with:
          clubhouseToken: ${{ secrets.CLUBHOUSE_TOKEN }}
          endStateName: Completed
          addReleaseInfo: true
