name: Move Stories to Testing
on:
  pull_request:
    types: ['review_requested']

jobs:
  update-clubhouse:
    runs-on: ubuntu-latest
    steps:
      - uses: farmersdog/clubhouse-workflow-action@master
        if: contains("${{ secrets.QA_USERNAMES }}"", "${{ github.event.pull_request.requested_reviewers[0].login }}")
        with:
          clubhouseToken: ${{ secrets.CLUBHOUSE_TOKEN }}
          endStateName: Ready for QA
