name: Move Stories to Testing
on:
  pull_request:
    types: ['review_requested']

jobs:
  update-clubhouse:
    runs-on: ubuntu-latest
    if: true
    steps:
      - uses: farmersdog/clubhouse-workflow-action@package-update
        with:
          clubhouseToken: ${{ secrets.CLUBHOUSE_TOKEN }}
          endStateName: Ready for QA
