name: Move Stories to Testing
on:
  pull_request:
    types: ['labeled']

jobs:
  update-clubhouse:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Test'
    steps:
      - uses: farmersdog/clubhouse-workflow-action@add-pull-request
        with:
          clubhouseToken: ${{ secrets.CLUBHOUSE_TOKEN }}
          endStateName: Ready for QA
