name: Move Stories to Testing
on:
  pull_request:
    types: ['review_requested']

env:
  QA_USERNAMES: ${{ secrets.QA_USERNAMES }}

jobs:
  update-clubhouse-on-review-request:
    runs-on: ubuntu-latest
    steps:
      - uses: farmersdog/clubhouse-workflow-action@master
        if: contains(env.QA_USERNAMES, github.event.pull_request.requested_reviewers[0].login)
        with:
          clubhouseToken: ${{ secrets.CLUBHOUSE_TOKEN }}
          endStateName: In Testing

  update-clubhouse-on-label:
    runs-on: ubuntu-latest
    steps:
      - uses: farmersdog/clubhouse-workflow-action@master
        if: contains(env.QA_USERNAMES, github.event.pull_request.requested_reviewers[0].login)
        with:
          clubhouseToken: ${{ secrets.CLUBHOUSE_TOKEN }}
          endStateName: In Testing
