name: Move Stories to Testing
on:
  pull_request:
    types: ['review_requested']

jobs:
  update-clubhouse:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJson(github.event.pull_request) }}
      - uses: farmersdog/clubhouse-workflow-action@master
        with:
          clubhouseToken: ${{ secrets.CLUBHOUSE_TOKEN }}
          endStateName: Ready for QA
